import {
  Heading,
  Text,
  Image,
  Center,
  UnorderedList,
  ListItem,
  Box,
  ListIcon,
  List,
  Button,
  Icon,
  Tooltip,
  IconButton,
  Stack,
  Badge,
  useColorMode,
} from "@chakra-ui/react";
import { SunIcon, MoonIcon, DownloadIcon } from "@chakra-ui/icons";
import Head from "next/head";
import { FaLinkedin, FaStackOverflow } from "react-icons/fa";
import { AiOutlineMail, AiFillGithub, AiFillYoutube } from "react-icons/ai";
import HomeSection from "../components/HomeSection/HomeSection";
import styles from "../styles/Home.module.scss";
import MediumIcon from "../icons/MediumIcon/MediumIcon";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Tooltip label="Try the dark mode toggle 🙂" placement="right" defaultIsOpen>
        <IconButton
          aria-label="button"
          onClick={toggleColorMode}
          className={styles.darkModeButton}
          icon={<Icon as={colorMode === "dark" ? SunIcon : MoonIcon} />}
        />
      </Tooltip>
      <Heading textAlign="center" colorScheme="blue" mb={5} marginTop={10}>
        Hi, I&apos;m Yamo and I&apos;m a software engineer based in Malmö, Sweden.
      </Heading>
      <div className={styles.container}>
        <Head>
          <title>Yamo Gebrewold&apos;s Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.leftSide}>
          <Center>
            <Image boxSize="200px" src="personal_image.jpg" alt="Yamo Gebrewold" />
          </Center>
          <Center>
            <Text maxWidth="lg" textAlign="center" fontSize="lg" mt={5}>
              I care about writing maintainable and extensible quality software. I love hacking{" "}
              <strong>JavaScript</strong> 💻 and I strive for constantly widening my knowledge about
              software engineering.
            </Text>
          </Center>
          <Center>
            <Box>
              <Text maxWidth="lg" textAlign="center" fontSize="lg" mt={5}>
                Let&apos;s connect:
              </Text>
              <List spacing="3">
                <ListItem>
                  <ListIcon as={FaLinkedin} />
                  <strong>LinkedIn</strong>:{" "}
                  <a
                    href="https://www.linkedin.com/in/yamo-gebrewold-495063151/"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Yamo Gebrewold
                  </a>
                </ListItem>
                <ListItem>
                  <ListIcon as={AiOutlineMail} />
                  <strong>Email</strong>:{" "}
                  <a href="mailto: yamo.gebrewold@gmail.com" target="_blank" rel="noreferrer">
                    yamo.gebrewold@gmail.com
                  </a>
                </ListItem>
                <ListItem>
                  <ListIcon as={AiFillGithub} />
                  <strong>GitHub</strong>:{" "}
                  <a href="https://github.com/Yamo93" target="_blank" rel="noreferrer">
                    Yamo93
                  </a>
                </ListItem>
                <ListItem>
                  <ListIcon as={FaStackOverflow} />
                  <strong>Stack Overflow</strong>:{" "}
                  <a
                    href="https://stackoverflow.com/users/11236310/yamo93"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Yamo93
                  </a>
                </ListItem>
              </List>
            </Box>
          </Center>
          <Center>
            <a href="./resume.pdf" className="no-hover" target="_blank">
              <Button colorScheme="teal" mt={5}>
                <DownloadIcon marginRight={2} />
                Download my resume
              </Button>
            </a>
          </Center>
          <Center>
            <Text maxWidth="lg" textAlign="center" fontSize="lg" mt={5}>
              Feel free to check out my software development articles and videos 👇:
            </Text>
          </Center>
          <Center>
            <List spacing="3">
              <ListItem>
                <ListIcon as={AiFillYoutube} />
                <strong>YouTube</strong>:{" "}
                <a
                  href="https://www.youtube.com/channel/UCdD-ao3ej7KpLMKORAaL_Iw"
                  target="_blank"
                  rel="noreferrer"
                >
                  Yamo Gebrewold
                </a>
              </ListItem>
              <ListItem>
                <ListIcon as={MediumIcon} />
                <strong>Medium</strong>:{" "}
                <a href="https://yamo-gebrewold.medium.com/" target="_blank" rel="noreferrer">
                  yamo-gebrewold
                </a>
              </ListItem>
            </List>
          </Center>
        </div>
        <div className={styles.rightSide}>
          <HomeSection heading="Work experience">
            <Box
              maxW="lg"
              borderWidth="1px"
              borderColor="teal"
              borderRadius="xl"
              padding="10px"
              mb="10px"
            >
              <Text fontSize="xl">
                Front-End Software Engineer <span className={styles.smallText}>@ Hypergene</span>
              </Text>
              <Text fontSize="sm">February 2021 - Present</Text>
            </Box>
            <Box maxW="lg" borderWidth="1px" borderColor="teal" borderRadius="xl" padding="10px">
              <Text fontSize="xl">
                Full-Stack Software Engineer <span className={styles.smallText}>@ GESHDO</span>
              </Text>
              <Text fontSize="sm">August 2019 - February 2021</Text>
            </Box>
          </HomeSection>

          <HomeSection heading="Education">
            <Box
              maxW="lg"
              borderWidth="1px"
              borderColor="teal"
              borderRadius="xl"
              padding="10px"
              mb="10px"
            >
              <Text fontSize="xl">
                B.Sc in Computer Science{" "}
                <span className={styles.smallText}>@ Linnaeus University</span>
              </Text>
              <Text fontSize="md">Complementary Studies for a Bachelor&apos;s Degree</Text>
              <Text fontSize="sm">August 2021 - Present</Text>
            </Box>
            <Box maxW="lg" borderWidth="1px" borderColor="teal" borderRadius="xl" padding="10px">
              <Text fontSize="xl">
                Computer Engineering{" "}
                <span className={styles.smallText}>@ Mid Sweden University</span>
              </Text>
              <Text fontSize="sm">August 2018 - July 2020</Text>
            </Box>
          </HomeSection>

          <HomeSection heading="Skills">
            <Stack direction="row">
              <Badge>JavaScript</Badge>
              <Badge colorScheme="green">TypeScript</Badge>
              <Badge colorScheme="red">C# and .NET</Badge>
              <Badge colorScheme="purple">NodeJS</Badge>
              <Badge colorScheme="blue">Web technologies</Badge>
            </Stack>
          </HomeSection>
        </div>
      </div>
    </>
  );
}
